import { model } from "mongoose";
import studentSchema from "../Schema/students.js";
import classSchema from "../Schema/class.js";
import teacherSchema from "../Schema/teacher.js";
import subjectSchema from "../Schema/subject.js";
import familySchema from "../Schema/family.js";
import feeTransactionSchema from "../Schema/feeTransaction.js";
import attendanceSchema from "../Schema/attendance.js";
import examSchema from "../Schema/exam.js";
import marksSchema from "../Schema/marks.js";
import progressReportSchema from "../Schema/progressReport.js";
import inventorySchema from "../Schema/inventory.js";
import inventoryDistributionSchema from "../Schema/inventoryDistribution.js";
import notificationSchema from "../Schema/notification.js";
import userSchema from "../Schema/user.js";
import timetableSchema from "../Schema/timetable.js";
import teacherAttendanceSchema from "../Schema/teacherAttendance.js";
import counterSchema from "../Schema/counter.js";
import settingsSchema from "../Schema/settings.js";

export const Student = model("Student", studentSchema);
export const Class = model("Class", classSchema);
export const Teacher = model("Teacher", teacherSchema);
export const Subject = model("Subject", subjectSchema);
export const Family = model("Family", familySchema);
export const FeeTransaction = model("FeeTransaction", feeTransactionSchema);
export const Attendance = model("Attendance", attendanceSchema);
export const Exam = model("Exam", examSchema);
export const Marks = model("Marks", marksSchema);
export const ProgressReport = model("ProgressReport", progressReportSchema);
export const Inventory = model("Inventory", inventorySchema);
export const InventoryDistribution = model("InventoryDistribution", inventoryDistributionSchema);
export const Notification = model("Notification", notificationSchema);
export const User = model("User", userSchema);
export const Timetable = model("Timetable", timetableSchema);
export const TeacherAttendance = model("TeacherAttendance", teacherAttendanceSchema);
export const Counter = model("Counter", counterSchema);
export const Settings = model("Settings", settingsSchema);
